"""
Django settings for text_generator project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.contrib.messages import constants as messages
from dotenv import load_dotenv


load_dotenv()
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-7kgtx^r0t)#@(oap$9rnvsts@!gswesi#_0y&v711os13frv40"

DEBUG = False

ALLOWED_HOSTS = ['*']

LOGIN_URL = '/login/'


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "generator",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "text_generator.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "text_generator.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

MESSAGE_TAGS = {
    messages.DEBUG:    'debug',
    messages.INFO:     'info',
    messages.SUCCESS:  'success',
    messages.WARNING:  'warning',
    messages.ERROR:    'danger',
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'generator.validators.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6, 
        }
    },
    {
        'NAME': 'generator.validators.UppercaseValidator',
    },
    {
        'NAME': 'generator.validators.NumericValidator',
    },
    {
        'NAME': 'generator.validators.SpecialCharacterValidator',
        'OPTIONS': {
            'special_characters': "!@#$%^&*()-_=+[]{};:,.<>?/"
        }
    },
]

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATIC_URL = "/static/"

STATICFILES_DIRS = [ BASE_DIR / 'static' ]



MEDIA_URL  = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
