# Generated by Django 5.2 on 2025-05-13 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0002_batchgeneration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchgeneration",
            name="count",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ]
            ),
        ),
    ]
