# Generated by Django 5.2 on 2025-05-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0003_alter_batchgeneration_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchgeneration",
            name="language",
            field=models.CharField(choices=[("en", "EN"), ("ru", "RU")], max_length=2),
        ),
    ]
