# Generated by Django 5.2 on 2025-05-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0004_alter_batchgeneration_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchgeneration",
            name="file_format",
            field=models.CharField(
                choices=[("docx", "DOCX"), ("rtf", "RTF"), ("txt", "TXT")], max_length=4
            ),
        ),
    ]
